// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F17d9s2lv8qWO6cM805lC0/kjr6a1VbTTR1bY8sp7OT9SYQeSWhIQEWAGWrPfruc/CgCIqgpLixkib+",
	"z5JI4OLiPn73AfiPIGJpxihQKYLOHwEHkTEqQH+4Bj4jEdxQPMMkwaME1LcRoxKoVH/iLEtIhCVhdP9X",
	"waj6TkRTSLH6628cxkEn+O/9cop986vY73HOeLBYLMIgBhFxkqlBgk4xJxpCmjGOOUnmyCEAMY7OYMJx",
	"DHEQBlPAMXBN7AAkn7e6YwlcfVwZNZ9MQEiBMIpzrglGhCIBEaOxQJKhO0wkGsGYcUBcDUXoJAid1ch5",
	"BkEnIFTCBDTpini7HvVAN4+J7M0sazLOMuCSGE7iSDLejzdx5ea8fxYswgDUKEM94foXyjn104swIFtP",
	"koLEMZZ6cTiOiWIKTq4cuiXPYXV/9GQtkUFExiRCWhjuZY4TFIPEJBFBWLCKjX6FSKqpWBTlnEPclfWt",
	"GZIUhMRphrBEd1MSTZGcAtIsQMWLQRiMGU+xDDpBjCW0JEmhnElIrrZrEQa5gK35vAgDDr/lRI3feas4",
	"53K+QvWtZ1El78+J8Ow5kZBW/9huJ9XYdjLMOZ6rzxTu5WnOBfPI9mWGf8sBRfpnJcpjkJaJ6jWU4QmE",
	"CI+EYujdFKj6iQPCHBBlKDUSL/JEijpHV3mkl7KeG4XcVqk8xRImjM8RGyOsFC/nRM5bAqggksyKDY9w",
	"JnMOsdJOtQKshkUJU7oINE8VETfXvcG7Qe9V/3rYG/TOgtB8c375qn/hfLi8GZafTn8qHzzrdU+H/Tfd",
	"of7qqnt9/cvl4Ozd6evuxavqV4PedW/4btD7503v2jw9uDzvOU8OeufdYf/y4vp1/+rdq0H3Ylj/etB7",
	"c6lmv/WI6+kUog8D+C0HnwRZ7tZ4OQDBch6B2uxIjaBZxSExhg1PMKFChoqH79WUHRK/R0p/FBPvcZop",
	"Qx7ELMpToLJzcHjkU6ViPN/8dqZi/sq4MwJ3wJuU02eb9TKXg22iW43SaR+8Phk8/9f3/3r5v4f/Pv7l",
	"xZuTYfv64J+Hg40irIlwVhcWbPZJtd0f4xM9Zj1J2B3E9TX9MgWlZHpfhF3flCXK1eid0hsOcblnzIi7",
	"ndlZrrHBlrARYwlgWltTQYdvCcbT1kgvrPVHGf/u8kkEath1Nh+KeVf8h34vYrF25dJY2nJz+xdvuuf9",
	"s3eng95Z72LY755f+yQpBSHwxGNmXucppi0OONZowVBZPO1ONJwCyjibkRhiFHGIgUqCE6HNIqEznGh/",
	"sF6WzBpLcnz8P2cTQhtVHFJMkvoybgTwvwukf0U4jjkIUVOC/7Ef9yKWug7SjOnhWoaFuGM8bpxv+YA7",
	"1bWy1XCFhTg4PPovdyLn8Q18shQtX1jDqEZdiyIQYsg+AG30geYZJPVD7hqej1/i70eH0TEcxQf4xfhk",
	"9DJqw2F8PH6BT6KDkY9bcJ8RDqLvmU5TgfQD1hCSFBxA6c599KLdDmvoUfFnzEFM1y/IPmRWFCLOJFZm",
	"g1EEOJqiXFSFWi1l3VJ9y9RD+322WWZNR38AzNcb+LXYS2j0vGLAnM11SXJ3YYVldjafJP1s1LFZlhrN",
	"R/GK12RcZmC3Wy0rAbUTIteUj/MkmW9Ug3Vm4sqqxgAEyFNGx4SndcIp3F01KvEF3C01GH2XEkrSPEUn",
	"KJpijiMJXDyrrOcC7krdPn7+okm3U0LPgU7kNOicNAlQnZqCToUtQRoJRhwiIDOI0YxgVFiFkiJ8MDqM",
	"juJjeD5+Mfl+ekJe/treyNVC213ebOTwl2CQvUbSR/nAkftGwtfbk4FrSFDGYUZYLpI5IkLkEKvYK1H2",
	"VzlljDJOGC+Mz5+0MCurrJDpX6yBRGJKsmGeJfAQXFyBw1mWEFBewYMs0XewN9lD710w/P7ZJ8LJFzh1",
	"Md4I5B2Y8EtZbo4wjR3UV5DC7ijw9yF6b4C0+gvHKaErZD0UZrNxhT2KzWv4sh5sr5C0S2ReE5NPEYTX",
	"Za8Wi28dEOscQ92OUDIDLnCi01pE+fhzuCcRm3CcTUmkf7hmXGr42teodEw0X0o+r2NxhqUErqb6/7ft",
	"1stu6/U/fvr54qo1fNP69+0fhy8Wf/OJzI0VGZwkl+Og83azC/8BC8WdzQ9ecTYmipO3dh795kfa3dyw",
	"qmJ+0XfGYpElk579eYi8ffpMeiHTFSc0IhlONGxSqoTgXgIVZEQSIucraYwgDK57gzf909677unp5c3F",
	"MAiDs576wpMv8CWsCnTW6DwUB085YAmO69h+n0/L0Ohh2+0O8KXu+taB0Tawaqt4aS2mekj0pAhVJrAZ",
	"9H6cKTQw/a+YiXSlsMaEMeFCKr/cuNX6CURxWgX//2BT6hOdBG8YTz1QH+6MedPXCYtwsmYs87M7ENDW",
	"adcb15EUfme0ebDlA+5w3RQ4ifD+kHFGJfNug5fjN1lcNTFPfH9kvi/CoEijXyulNYw2wXk3V5alKUuS",
	"y6kynlGRxDXxk9Z8nWVcie+nUmamVEfomBUlQGwQuLXggcizjHG5Yno1/ztB96qPrs0DQa3ip35UftJA",
	"4gptIcqMIqMUUzwBBcNDDZuXBpkVQblAuSB0gphZpF6V2Ps/2tPeg5jMq/UoGScp5nPHiWgKcJJoKtRr",
	"avlE2nzHlCUxcKSXYStfBURVaM6so713sNfW1a4MKM5I0AmO9tp7bQPKpnp39nU9o5Wwif44AW8UIzmB",
	"GQgViOEJoTrlkxChsbuncmJqJLp+IkKUsTtQImPKJypwQDEW0xHDPP67sA+r4GEPDYw9FQhT8yQRUjFz",
	"BoizBPYCvRbD3n4cdALlYHSh51wtQK2L4xSkrsC+XV3HjySRwC1daDQ3BI3HEKn15EYZ+meBEqugE/yW",
	"A5+XImMLeeGW9eSioreZCIOXfFO6tb/tZl0tv9bnv6TJHHGQOacFEXKKy8KmCryV5I2lrhYQYx50PbSB",
	"yjHXmlUSuE1h9MGE2Yr4VpRps/Vn6foZ32t8RfN0BFxJfEEds+Q2zJ6QlMgKATGMcZ7IoHPYDoPUjBt0",
	"DtptDb/sp3pq1sMrY1KsMuoEoIE4ai90usSkU1DRPdFAonnL11Ww5MdtWG3BOGy3P1nPxUrB2tN80XUs",
	"ie6CUHZoJcm5CIPj9sHjN4LcUOULGCe/Q4xaqG9KMkomUyK0pTeOS9Nz9Pj0/Mj4iMQxUNRCpzhJgKME",
	"Rx/Kih7RWlM1oxlwTS3TdD7/hJvZSGefqvgfJ0gAnynTZx5Usx81DboUuX1Py48LNLSZdyHG21slsiJP",
	"lT+1HqIs2ltRUnqPlcd7G3QVf4JbNea+2l+6H5W5bq87tLlw5Q1zTxLWen2M7DhVTFN1X3YohcMGMLG7",
	"pL34Wkd2WhsZ6QhGsmUqr6Cq0TIacsoAxlRXP48dWC2P+JRPYTFX7Qv2QmwUbieCvEbjD3ZAgFPlM8v+",
	"C+vvUkGtMBu0zatasFTSCgivaKtOvujwjgmPsjpvQqGxGq8b162RJvPWaleApprmpsgH65jyBxbPPxn3",
	"K0X5RTW3oFRz8YjqV61zeyRAP+Bo3841znIc6e7AXfn7YvKoknAMjg934Nu7UcRyqlxW9AFiFOv4EXHI",
	"QMdeY0wSFYLpfcFSQppJS9zLXZghpsLf+cr8qIU4loA07v167JP2PMbKbGuQWC6bLZIVK22PlLfW0Q2V",
	"hdd2rZA1VDP2wT6LhWARwaZRy6mf+swVy+Uj2itfBXhh7VbFTB3XOWCIq9mTLwvCfwPQuJBsJa5biXaR",
	"49rXHRTNIq4bGoSLRZfZsQIcF3Z92YlRE2E9yFVZoHgMKfb2uOzY+24BfpedKxUAbDbhc7pi3TC5UwQ8",
	"cFp3vjIcbJbmdjBahSx7iBpVscWdModXJa+BxiZ/W2mCSgj90BA2rmqjnqCiMLtQyo+CxIefRSkNJ00O",
	"QNjjEp8ZHR/vwJUq50GZRGOW03j32NMuWnw96m82saqgm8xA0RHXqPe9+2iK6UTHvoW0uI13usqEKNxV",
	"gKdt7C2KNuuxpoWC3UrH7A4x5xcVKg9tV6mm1Jup/trD5mpjpz24EBbeOtTFpYQDjuc2tPmKPLhZ+Uoi",
	"aQtgbdJepuPNr8emYUpYXTVZLJsjuCPStLT4To94tNVM9YixYb3BaystPfikBGyXRC4Y/xmyyHXlfLkj",
	"r12oH9yTr8qBmq10VGQb5ft93xwYbNY89bNAd/YAnU0hT7HSxQmZaWtfnj7E1DZPhyiGBCalE40hIsI+",
	"pT5fZkB/fNVFQjIO9cqQmvWqLNY9jqZWTnvu2JVWTzL6APZy9fZMKcxwkmP5TXrVp8xVpWak5QG71eyq",
	"qitG1TXdPWJgz5wmIL2nrlI2M21I2kgq/rovI5lnCZhui5ou25MKGtyYZBdnCTx7QHfTmSbPPQPwaMi6",
	"dsxgG2Nw3HwS2+FSxeEajsdPSvsX7RjZSW7BI0SVTMM3YOGM6ivbUePFGlMX+jtWzhXOWxqp+ogiRCwz",
	"x+iTORrrDkWI0WheHASzzbDe9stBxahu14JpZnUmaDr05utdWV5J0NysEm6cV4O47Y+UNTWEfrbWOf9p",
	"s6106amR7qmR7qGNdB7bsdYc+UOqXzgpcxkeXOWLkKyyTjim0qAqkwTR0Akxqk2lOW37EKhV5Cu+VKh1",
	"8NgEfByMizS7nmDck736cmNELaIfi6BUsJiQGaw7DKP7Bg/bbXT5EyLjIvWqc75EIJ5TSuhkz5/SOScz",
	"oOaqBh82WMVt5mGb/3AbZhZV0+w+56zuNeBETs23Zm1ZeQ6xKfg9AxxJMls2KDknoMpjMuyOFgnohrDV",
	"PfW4TeRYtLythIsFLfFTquVzBiLV/V7WJO3+NkYe5dGxRkkqDtQRas7n2IsWKhL1CuRacWo/eunATv0X",
	"gs7fgGy+AtM2WchQg2RmuUcyzfHgPymXZpBV0Xycilr1PPOOk/Wb1CLXxD0l5jeAwx1U+Mzp4qLER6i+",
	"ku0b6WfVQrjZIigcpNnzESAPJwmKOFE2wqyORGCuZpxqjDUP0fP2ESoui65cEC2nwO+IgAZIOAAckzWY",
	"cOstq15wICSWubnTZHmo/+Zq4zUW9rX6PRa+INES7sGnn66qW5ljLbbVJ+UfeIrdnLJ/2AH0Gz3vhsxn",
	"/RixnvLpFPEn8U2Vi2Ya+h6e8p5PeYSH5j1zq+K+U8P6t/0/SLzYNqrGVPsE58iPiqseVCAuBrXtXGtN",
	"UPUSK+Je5abVOsNyWmo1ideeD97i7ovbbcL+ek/WFx7zP1Vq13aBfxMpkUJAbRXCYxjCzSBE41RzCw3h",
	"Xq30JkF+mOsrar5wTW/vpplznUd/Ev8HYu5lWmU0N9chFcJtgO6t+T8zemqf8F1xFueRxpPmoSAMcp7Y",
	"e7tEZ38fZ2TPuZZrf3YQ1NHptVS4dNI0hjA/t7Ya65xF+v/BzCBhWQpU+kbt7O/ra9WmTMjOSfukrce6",
	"XS7f67lWri4rL/9y7hqrtp7WqbtxAlbnXrFyhOUVlmHjndbla14alodHGmbf8LrZ+Pq7bpmwNcJC+STT",
	"/K4UgLPEvQ3tO1vPbY1w9AHiZ1UOlUWY+jTdqp9zxhwz7rtWzBla2+PF7eI/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
