// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F17d9s2lv8qWO6cM805lC0/kjr6a1VbTTR1bY8kp7OT9SYQeSWhIQEWAGWrPf7uc/CgCIqgpLixkib+",
	"z5JI4OLiPn73AfiPIGJpxihQKYLOHwEHkTEqQH8YAp+TCK4pnmOS4HEC6tuIUQlUqj9xliUkwpIwuv+r",
	"YFR9J6IZpFj99TcOk6AT/Pd+OcW++VXs9zhnPLi/vw+DGETESaYGCTrFnGgEacY45iRZIIcAxDg6gynH",
	"McRBGMwAx8A1sQOQfNHqTiRw9XFl1Hw6BSEFwijOuSYYEYoERIzGAkmGbjGRaAwTxgFxNRSh0yB0ViMX",
	"GQSdgFAJU9CkK+LtetQD3ShiOZVDiWUuDAkTnCcy6ATd01H/TS9YXes5mUC0iBJAQr+E2ARhlAvgfxcI",
	"m+GCMACap0HnbTnK+eXpT72zIAzOevq77qh3FtyEAdzhNFObVD5qqRaSq/Xch0E3j4nsze0GZpxlwCUx",
	"+40jyXg/3rR31+f9MzUUqFFGeoL1L5Rz6qfvw4BsPUkKEsdY6i3AcUwU63By5dAteQ6rnNWTtUQGEZmQ",
	"CGmRvZM5TlAMEpNElKxh418hkmoqFkU55xB3ZV2ARiQFIXGaISzR7YxEMyRngDQLUPFiEAYTxlOstjzG",
	"ElqSpODbBLXF2/L5Pgw4/JYTNX7nreKcy/kK1TeeRZW8PyfCs+dEQlr9Y7udVGPbyTDneKE+U7iTpzkX",
	"zKOBlxn+LQcU6Z+Vwk1AWiaq11CGpxAiPBaKobczoOonDghzQJSh1OilyBMp6hxd5ZFeynpuFHJbpfIU",
	"S5gyvjCaKCDKOZGLlgAqiCTzYsMjnMmcQ6xsiFoBVsOihE0dbb0e9gbvBr1X/eGoN9Daqr85v3zVv3A+",
	"XF6Pyk9WrfUnV7fD4Ko7HP5yOTh7d/q6e/Gq+tWgN+yN3g16/7zuDc3Tg8vznvPkoHfeHfUvL4av+1fv",
	"Xg26F6P614Pem8ufjBmpievpDKIPA/gtB58EWe7WeDkAwXIegdrsSI2gWcUhMeYXTzGhQoaKh+/VlB0S",
	"v0dKfwLXksUsylOgsnNweORTpWI83/x2pmL+yrhzArfAm5TT50H0MpeDbaJbjdJpH7w+GTz/1/f/evm/",
	"h/8+/uXFm5NRe3jwz8PBRhHWRDirCws2+6Ta7o/x3B6zniTsFuL6mn6ZgVIyvS/Crm/GEuUQ9U7pDYe4",
	"3DNmxN3O7CzX2GBL2JixBDCtramgw7cEgwdqpBfW+qOMf3f5JAI17DqbD8W8K/5DvxexWAMOaSxtubn9",
	"izfd8/7Zu9NB76x3Mep3z4c+SUpBCDz1mJnXeYppiwOONaYxVBZPuxONZoAyzuYkhhhFHGKgkuBEaLNI",
	"6Bwn2h+slyWzxpIcH//P2ZTQRhWHFJOkvoxrg1T0rwjHMQchakrwP/bjXsRS10GaMT1cy7AQt4zHjfMt",
	"H3CnGipbDVdYiIPDo/9yJ3Ie38AnS9HyhTWMatS1KAIhRuwD0EYfaJ5BUj/kruH55CX+fnwYHcNRfIBf",
	"TE7GL6M2HMbHkxf4JDoY+7gFdxnhIPqe6TQVSD9gDSFJwYG97txHL9rtsIZxFX8mHMRs/YLsQ2ZFIeJM",
	"YmU2GEWAo5kCtJVlqqWsW6pvmXpov882y6zp6A+A+XoDvxZ7CY3xVwyYs7kuSe4urLDMzuaTpJ+NOjbL",
	"UqP5KF7xmozLDOx2q2UloHZC5JrySZ4ki41qsM5MXFnVGIAAecrohPC0TjiF26tGJb6A26UGo+9SQkma",
	"p+gERTPMcSSBi2eV9VzAbanbx89fNOl2Sug50KmcBZ2TJgGqU1PQqbAlSCPBiEMEZA4xmhOMCqtQUoQP",
	"xofRUXwMzycvpt/PTsjLX9sbuVpou8ubjRz+Egyy10j6KB84ct9I+Hp7MnANCco4zAnLRbJARIgcYhV7",
	"Jcr+KqeMUcYJ44Xx+ZMWZmWVFTL9izWQSMxINsqzBB6CiytwOMsSAsoreJAl+g72pnvovQuG3z/7RDj5",
	"AqcuxhuDvAUTfulUBMI0dlBfQQq7pcDfh+i9AdLqLxynhK6Q9VCYzSYV9ig2r+HLerC9QtIukXlNTD5F",
	"EF6XvVosvnVArHMMdTtCyRy4wIlOvhHl48/hjkRsynE2I5H+Yci41PC1r1HphGi+lHxex+IMSwlcTfX/",
	"b9utl93W63/89PPFVWv0pvXvmz8OX9z/zScy11ZkcJJcToLO280u/AcsFHc2P3jF2YQoTt7YefSbH2l3",
	"c8OqivlF3xmLRZZMevbnIfL26TOxzEauTetUUpdLaao5S05oRDKcaLSlNBDBnQQqyJgkRC5Wsh9BGAx7",
	"gzf909677unp5fXFSKcs1ReeNIMvz1WAukafoxh/ygFLcDzO9uJxWkZUD5MSd4AvVVi2jqe2QWNbhVlr",
	"odhDgi5FqLKczVj54yyoQfd/xQSmK4U1JkwIF1K588at1k8gitNqzPAPNqM+0UnwhvHUA/Xhzpg3652w",
	"CCdrxjI/uwMBbZ12veEgSeF3RpsHWz5QqYqkwEmE90eMMyqZdxu8HL/O4qqJeeL7I/NduS6bfR8qpTWM",
	"NjF9N1eWpSm5ksuZMp5Rkfs1YZfWfJ2cXEkLzKTMTB2S0Akr6pvYAHdrwQORZxnjcsX0av53gu5VHw3N",
	"A0GtnKl+VH7SIOkKbSHKjCKjFFM8BYXeQ422lwaZFbG8QLkgdIqYWaReldj7P9rT3oOYhK31KBknKeYL",
	"x4loCnCSaCrUa2r5RNo0yYwlMXCkl2ELZgWyVSDQrKO9d7DX1kWyDCjOSNAJjvbae22D5WZ6d/Z1GaSV",
	"sKn+OAVv8CM5gTkIFb/hKaE6U5QQoSG/p+BiSiu67CJClLFbUCJjqi4q3kAxFrMxwzz+u7APq5hjDw2M",
	"PRUIU/MkEVIxcw6IswT2Ar0Ww95+rKuxQur60LlagFoXxylIXV5+u7qOH0kigVu60HhhCJpMIFLrsSXc",
	"/lmgxCroBL/lwBelyNj6X7hlsbwoBG4mwuAl35RuyXC7WVertvX5L2myQBxkzmlBhJzhsh6q4nUleROp",
	"iwzEmAddRm2gcsK1ZpUEblNPfTBhtty/FWXabP1Zun7Gdxpf0TwdA1cSX1DHLLkNsyckJbJCwLK54LAd",
	"BqkZN+gctNsaftlP9Yyuh1fGpFhl1HlDA3HUXugsi8nCoKI1pIFE85avZWLJj5uw2l9y2G5/soaSlTq3",
	"p7Ok61gS3eKh7NBKbvQ+DI7bB4/f5XJNlS9gnPwOMWqhvqnkKJlMidCW3jguTc/R49PzI+NjEsdAUQud",
	"4iQBjhIcfSgLgURrTdWMZsA1tUzT+fwTbmYjnX0qgVOcIAF8rkyfeVDNftQ06FLk9j39TC7Q0GbehRhv",
	"b5TIijxV/tR6iLLWb0VJ6T1WHu9t0FX8CW7UmPtqf+l+VKbIve7QptBF2fZTjQeN18fIjlPFNFX3ZYdS",
	"OGwAU7tL2ouvdWSntZGRjmAkW2YAC6oaLaMhpwxgTFH289iB1aqKT/kUFnPVvmAvxEbhdiLIazT+YAcE",
	"OMVBs+y/sP4uFdQKs0HbvKoFSyWtgPCKturkiw7vmPAoq/MmFBqr8bpx3RppMm+JdwVoqmmuizSyjil/",
	"YPHik3G/Usu/r+YWlGreP6L6VcvjHgnQDzjat3ONsxxHuqlwV/6+mDyqJByD48Md+Hab3FVx/geIUazj",
	"R8QhAx17TTBJVAim9wVLCWkmLXEvd2GGmAp/FyvzoxbiWALSuPfrsU/a8xgrs61BYrlstkhWrLQ9Ut5a",
	"RzdUOi3ESytkDdWcfbDPYiFYRLDp73LKrj5zxXL5iPbKVzi+t3arYqaO6xwwxNXsyZcF4b8BaFxIthLX",
	"rUS7yHHt68aLZhHXfRDCxaLL7FgBjgu7vmzgqImwHuSqLFA8hhR7W2N27H23AL/LhpcKADab8Dldse6z",
	"3CkCHjgdP18ZDjZLcxsfrUKWrUeNqtjiTpnDq5JDoLHJ31Z6pxJCPzSEjavaqCeoKMwulPKjIPHhZ1FK",
	"w0mTAxD2lMVnRsfHO3ClynlQJtGE5TTePfa0ixZfj/qbTawq6CYzUDTSNep97y6aYTrVsW8hLW6/nq4y",
	"IQq3FeBp+4GLos16rGmhYLfSaLtDzPlFhcoj24yqKfVmqr/2sLnaD2rPO4SFtw51cSnhgOOFDW2+Ig9u",
	"Vr6SSNoCWJu0l2mU8+uxaZgSVldNFsvmCG6JNC0tvkMnHm01Uz1ibFhv8NpKSw8+KQHbJZELxn+GLHJd",
	"OV/uyGsX6gd35KtyoGYrHRXZRvl+3zfnDJs1T/0s0K09d2dTyDOsdHFK5tral4cWMbU91yGKIYFp6URj",
	"iIiwT6nPlxnQH191kZCMQ70ypGa9Kot1j6OplUOiO3al1QOQPoC9XL09igpznORYfpNe9SlzVakZaXnA",
	"bjW7quqKUXVNd08m2KOqCUjvYa2UzU0bkjaSir/uy0jmWQKm26Kmy/aAgwY3JtnFWQLPHtDddKbJc48O",
	"PBqyrp1O2MYYHDcf4Ha4VHG4huPxk9L+RTtGdpJb8AhRJdPwDVg4o/rKdtR4scbUhf6OlXOF85ZGqj6i",
	"CBHLzOn7ZIEmukMRYjReFOfHbDOst/1yUDGq27VgmlmdCZrOyvl6V5Y3GTQ3q4Qb59UgbvuTaE0NoZ+t",
	"dc5/SG0rXXpqpHtqpHtoI53Hdqw1R/6Q6hdOylyGB1f5IiSrrFOOqTSoyiRBNHRCjGpTaQ7pPgRqFfmK",
	"LxVqHTw2AR8H4yLNricY92SvvtwYUYvoxyIoFSwmZA7rDsPovsHDdhtd/oTIpEi96pwvEYjnlBI63fOn",
	"dM7JHKi54cGHDVZxm3nY5j/chpn7qml2n3NW9xpwImfmW7O2rDyH2BT8ngGOJJkvG5ScE1DlMRl2S53b",
	"Dn1hq3vqcZvIsWh5WwkXC1rip1TL5wxEqvu9rEna/W2MPMqjY42SVByoI9Scz7H3M1Qk6hXIteLUfvTS",
	"gZ36LwSdvwHZfAWmbbKQoQbJzHKPZJrjwX9SLs0gq6L5OBW16nnmHSfrN6lFrol7SsxvAIc7qPCZ08VF",
	"iY9QfZPbN9LPqoVws0VQOEiz5yNAHk4SFHGibIRZHYnA3Og40xhrEaLn7SNU3IRduf1azoDfEgENkHAA",
	"OCZrMOHWW1a94KC8RaY81H99tfEaC/ta/R4LX5BoCffg009X1a3MsRbb6pPyDzzFbk7ZP+wA+rWed0Pm",
	"s36MWE/5dIr4k/imykUzDX0PT3nPpzzCQ/OeuVVx36lh/dv+HyS+3zaqxlT7hJX/GvCgAnExqG3nWmuC",
	"qpdYEfcGOK3WGZazUqtJvPZ88BZ3X9xsE/bXe7K+8Jj/qVK7tgv8m0iJFAJqqxAewxBuBiEap5pbaAj3",
	"aqU3CfLDQl9R84Vrens3zZzrPPqT+D8Qcy/TKuOFuQ6pEG4DdG/MP9HRU/uE74qzOI80njQPBWGQ88Te",
	"2yU6+/s4I3vOtVz784Ogjk6HUuHSadMYwvzc2mqscxbpfyMzh4RlKVDpG7Wzv6+vVZsxITsn7ZO2Hutm",
	"uXyv51q5uqy8/Mu5a6zaelqn7toJWJ17xcoRlldYho1XYZeveWlYHh5pmH3D62bj6++6ZcLWGAvlk0zz",
	"u1IAzhL3NrTvbD23NcbRB4ifVTlUFmHq03Srfs4Zc8K471oxZ2htj+9v7v8TAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
