// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F17d9s2lv8qWO6cM805lCU7Tpror1VtNdHUtT2SnM5O1ptA5JWEhgRYAJSj9vi7z8GDIiiCkuLGipv4",
	"r0QSCVxc3MfvPgD/EUQszRgFKkXQ/SPgIDJGBegPI+ALEsEVxQtMEjxJQH0bMSqBSvVfnGUJibAkjLZ/",
	"FYyq70Q0hxSr//2NwzToBv/dLqdom19Fu88548Ht7W0YxCAiTjI1SNAt5kRjSDPGMSfJEjkEIMbRKcw4",
	"jiEOwmAOOAauiR2C5MtWbyqBq49ro+azGQgpEEZxzjXBiFAkIGI0FkgydIOJRBOYMg6Iq6EInQWhsxq5",
	"zCDoBoRKmIEmXRFv16Me6EURy6kcSSxzYUiY4jyRQTfonYwHb/rB+lrPyBSiZZQAEvolxKYIo1wA/7tA",
	"2AwXhAHQPA26b8tRzi5OfuqfBmFw2tff9cb90+A6DOAjTjO1SeWjlmohuVrPbRj08pjI/sJuYMZZBlwS",
	"s984kowP4m17d3U2OFVDgRplrCfY/EI5p376NgzIzpOkIHGMpd4CHMdEsQ4nlw7dkuewzlk9WUtkEJEp",
	"iZAW2Y8yxwmKQWKSiJI1bPIrRFJNxaIo5xzinqwL0JikICROM4QlupmTaI7kHJBmASpeDMJgyniK1ZbH",
	"WEJLkhR8m6C2eFc+34YBh99yosbvvlWcczlfofras6iS92dEePacSEir/9ltJ9XYdjLMOV6qzxQ+ypOc",
	"C+bRwIsM/5YDivTPSuGmIC0T1WsowzMIEZ4IxdCbOVD1EweEOSDKUGr0UuSJFHWOrvNIL2UzNwq5rVJ5",
	"giXMGF8aTRQQ5ZzIZUsAFUSSRbHhEc5kziFWNkStAKthUcJmjrZejfrDd8P+q8Fo3B9qbdXfnF28Gpw7",
	"Hy6uxuUnq9b6k6vbYXDZG41+uRievjt53Tt/Vf1q2B/1x++G/X9e9Ufm6eHFWd95ctg/640HF+ej14PL",
	"d6+GvfNx/eth/83FT8aM1MT1ZA7RhyH8loNPgix3a7wcgmA5j0BtdqRG0KzikBjzi2eYUCFDxcP3asou",
	"id8jpT+Ba8liFuUpUNk9PHrqU6ViPN/8dqZi/sq4CwI3wJuU0+dB9DJXg22jW43S7Ry+fjF89q/v//Xy",
	"f4/+ffzL8zcvxp3R4T+PhltFWBPhrC4s2OyTars/xnN7zHqSsBuI62v6ZQ5KyfS+CLu+OUuUQ9Q7pTcc",
	"4nLPmBF3O7OzXGODLWETxhLAtLamgg7fEgweqJFeWOtPMv691ZMI1LCbbD4U8675D/1exGINOKSxtOXm",
	"Ds7f9M4Gp+9Ohv3T/vl40Dsb+SQpBSHwzGNmXucppi0OONaYxlBZPO1ONJ4DyjhbkBhiFHGIgUqCE6HN",
	"IqELnGh/sFmWzBpLcnz8P2MzQhtVHFJMkvoyrgxS0b8iHMcchKgpwf/YjwcRS10Hacb0cC3DQtwwHjfO",
	"t3rAnWqkbDVcYiEOj57+lzuR8/gWPlmKVi9sYFSjrkURCDFmH4A2+kDzDJL6IXcNz6Yv8feTo+gYnsaH",
	"+Pn0xeRl1IGj+Hj6HL+IDic+bsHHjHAQA890mgqkH7CGkKTgwF537qfPO52whnEVf6YcxHzzguxDZkUh",
	"4kxiZTYYRYCjuQK0lWWqpWxaqm+Zemi/zzbLrOnoD4D5ZgO/EXsJjfHXDJizuS5J7i6ssczO5pOkn406",
	"NstSo/koXvGajIsM7HarZSWgdkLkmvJpniTLrWqwyUxcWtUYggB5wuiU8LROOIWby0YlPoeblQaj71JC",
	"SZqn6AWK5pjjSAIXTyrrOYebUrePnz1v0u2U0DOgMzkPui+aBKhOTUGnwpYgjQQjDhGQBcRoQTAqrEJJ",
	"ET6cHEVP42N4Nn0++37+grz8tbOVq4W2u7zZyuGHYJC9RtJH+dCR+0bCN9uToWtIUMZhQVgukiUiQuQQ",
	"q9grUfZXOWWMMk4YL4zPn7Qwa6uskOlfrIFEYk6ycZ4lcBdcXIHDWZYQUF7BgyzRd3AwO0DvXTD8/sln",
	"wsnnOHUx3gTkDZjwS6ciEKaxg/oKUtgNBf4+RO8NkFb/w3FK6BpZd4XZbFphj2LzBr5sBttrJO0TmdfE",
	"5HME4XXZq8XiOwfEQ5ZANVelgs9apuqEYS6gNeOYUCUsLAGEhSAz9Ukyo4w0IhlODtCPhJaPZsBTIoQi",
	"V4NWWOAk1/BAGVe1x71czhknvxvx++4iA/rjq94TBDTOGKFSHLg5sNOfV+FzNeVl6a7Jmc6i1C0lJQvg",
	"Aic6vUgUijmDjyRiM46zOYn0DyPGpQboA427p0TvfDnlJiHKsJTA1VT//7bTetlrvf7HTz+fX7bGb1r/",
	"vv7j6Pnt37zEWqXASXIxDbpvt4OUH7BQ+7/9wUvOpkTJyrWdp6fU9SqLsQTHXKeEuvHVYbhuwK3AbBRQ",
	"ZmRSrFKhG3NKlbzp7a1HSlcL/URHmJudrfhD9J1xIWS1p0/+fMyyez7z3vlXUFdDOoWCaqiszCeCjxKo",
	"IBOSELlcS10FYTDqD98MTvrveicnF1fnY51vVl94ckS+JGWByBsBg9qkEw5V+dtd8k/KcPhuCuAO8FAF",
	"a+dgeBcovVOMvBFH3yViVoQqt9cc6Hya+zOh2V8x++xKYY0JU8KFVFiscav1E4jitBrw/YPNqU90Erxl",
	"PPVAfbhT5i1ZJCzCyYaxzM/uQEBbJz1vLE9S+J3R5sFWD1RKWilwEuH2mHFGJfNug5fjNRf3yPd75rty",
	"XbZ0MlJKaxhtEjIK7TVnxnI5V8YzKhL3JmbWmq8zy2s5nbmUmSkiEzplRXEam6jLWvBA5FnGuFwzvZr/",
	"3aB3OUAj80BQq0WrH5WfNGFQhbYQZUaRUYopnoEKvUIdKq0MMisSMQLlgtAZYmaRelXi4P9oX3sPYrLt",
	"1qNknKSYLx0noinASaKpUK+p5RNpc1xzlsTAkV6GrXYWYYnCt2YdnYPDg46ucGZAcUaCbvD0oHPQMTB1",
	"rnenrWtYrYTN9McZeCNXyQksQCi8j2eEahyfEKHjNU+1zNTFdM1MhChjN6BExpTMFPpEMRbzCcM8/ruw",
	"D6uA8QANjT0VCFPzJBFSMXMBOvZQEcGKvYNYl9KF1MW9M7UAtS6OU5C6N+Dt+jp+JIkEbulCk6UhaDqF",
	"SK3H1t8Hp4ESq6Ab/JYDX5YiY4u34Y6dDkUVdzsRBi/5pnTrvbvNul5yr89/QZMl4iBzTgsi5ByXxWyk",
	"/s8RnkpdISLGPOgaeAOVU641qyRwl2L4nQmzvRo7UabN1p+l62f8UeMrmqcT4EriC+qYJbdh9oSkRFYI",
	"WEXbR50wSM24Qfew09Hwy36qp+M9vDImxSqjTvoaiKP2QkflJoWGir6eBhLNW75+lxU/rsNqc9BRp/PZ",
	"uoHWmhQ8bUE9x5Lo/hxlh9YS27dhcNw5vP8WpSuKbcoCYtRCA1OGUzKpMx3KwGnHpel5ev/0/Mj4hMQx",
	"UNRCJzhJgKMERx/KKi7RWlM1o2VeRtH57DNuZiOdAyqBU5wgAXyhTJ95UM3+tGnQlci1Pc1oLtDQZt6F",
	"GG+vlciKPFX+1HqIslHDipLSe6w83ttAp0OCazVmW+0vbUdlfcPrDm39Q5Q9W9V40Hh9jOw4VUxTdV92",
	"KIXDhjCzu6S9+EZHdlIbGekIRrJV+ragqtEyGnLKAMZU1L+MHVgvifmUT2ExV+0L9kJsFG4vgrxB4w/3",
	"QIBT2TXL/gvr70pBrTAbtM2rWrBS0goIr2irTr7o8I4Jj7I6b0KhsRqvG9etkSbz1ufXgKaa5qqoAeiY",
	"8gcWLz8b9yuNGLfV3IJSzdt7VL9qb4NHAvQDjvbtXeMsx5HuCN2Xvy8mjyoJx+D4aA++3SZ3VZz/AWIU",
	"6/gRcchAx15TTBIVgul9wVJCmklL3Mt9mCGmwt/l2vyohTiWgDTu/Xrsk/Y8xsrsapBYLpstkhUrbY+U",
	"t9bRDZVO//fKCllDtWAf7LNYCBYRbJrznJq5z1yxXN6jvfJV/W+t3aqYqeM6BwxxNXvysCD8NwCNC8lW",
	"4rqTaBc5rrbummkWcd3EIlwsusqOFeC4sOur7puaCOtBLssCxX1Isbevac/edwfwu+pWqgBgswlf0hXr",
	"Jtm9IuCh0671leFgszS3a9UqZNk31qiKLe6UObwqOQIam/xtpfEtIfRDQ9i4ro16gorC7EMpPwkSH30R",
	"pTScNDkAYY/IfGF0fLwHV6qcB2USTVlO4/1jT7to8fWov9nEqoJuMwNFF2Sj3vc/RnNMZzr2LaTFbbbU",
	"VSZE4aYCPG0zd1G02Yw1LRTsVbqk94g5H1SoPLadxJpSb6b6aw+bq8289rBKWHjrUBeXEg44XtrQ5ivy",
	"4Gbla4mkHYC1SXuZHkC/HpuGKWF11WSxbI7ghkjT0uI7MeTRVjPVPcaG9QavnbT08LMSsFsSuWD8F8gi",
	"15Xz5Z68dqF+8JF8VQ7UbKWjIrso3+9tc0i0WfPUzwLd2EOTNoU8x0oXZ2ShrX154hRT2zAfohgSmJVO",
	"NIaICPuU+mwbnpGQjEO9MqRmvSyLdfejqZUTvnt2pdXTqz6AvVq9PUdc9pB/e171MXNVqRlpecBuNbuq",
	"6quDBRVNd4+V2HPGCUjvSbuULUwbkjaSir/uy0jmWQKm26Kmy/Z0igY3JtnFWQJP7tDddKrJc8993Buy",
	"rh0t2cUYHDefvne4VHG4huPxo9L+RTtG9pJb8AhRJdPwDVg4o/rKdtR4scHUhf6OlTOF81ZGqj6iCBHL",
	"zNUJyRJNdYcixGiyLA7/2WZYb/vlsGJUd2vBNLM6EzQddPT1rqyuoWhuVgm3zqtB3O7HCJsaQr9Y65z/",
	"hOFOuvTYSPfYSHfXRjqP7dhojvwh1S+clLkMD67yRUhWWWccU2lQlUmCmEOpjGpTaU5Y3wVqFfmKhwq1",
	"Du+bgE+DcZFm1yOMe7RXDzdG1CL6qQhKBYsJWcCmwzC6b/Co00EXPyEyLVKvOudLBOI5pYTODvwpnTOy",
	"AGqu5/Bhg3XcZh62+Q+3Yea2aprd55zVvQacyLn51qwtK88hNgW/p4AjSRarBiXnBFR5TIbdUOeqSl/Y",
	"6p563CVyLFre1sLFgpb4MdXyJQOR6n6vapJ2fxsjj/LoWKMkFQfqCDXnc+zlGhWJegVyozh17r10YKf+",
	"C0Hnb0A2X4FpmyxkqEEys9wjmeZ48J+USzPIumjeT0Wtep55z8n6bWqRa+IeE/NbwOEeKnzmdHFR4iNU",
	"X8P3jfSzaiHcbhEUDtLs+QSQh5MERZwoG2FWRyIwNxvNNcZahuhZ5ykqrjGvXF0u58BviIAGSDgEHJMN",
	"mHDnLatecFDeIuNclnS59RoL+1r9HgtfkGgJ9+DTz1fVrcyxEdvqk/J3PMVuTtnf7QD6lZ53S+azfoxY",
	"T/l4iviz+KbKRTMNfQ+Pec/HPMJd8565VXHfqWH9W/sPEt/uGlVjqn3C2p98uFOBuBjUtnNtNEHVS6yI",
	"e7mdVusMy3mp1STeeD54h7svrncJ++s9WQ885n+s1G7sAv8mUiKFgNoqhMcwhNtBiMap5hYawr1a6U2C",
	"/LDUV9Q8cE3v7KeZc5NHfxT/O2LuVVplsjTXIRXCbYCuTqlgGXnu8+rpu2FFUZXDNG4zjooTCDrVUmR5",
	"zV8+MkW9hEUfQpRT9e+T8q8h3cEhlgkZo4gPUU/uJz3kudb1geSI6h7eZoseE0SP0OIRWvhSWKubhUxz",
	"A18zm75ARM+iKPbZuUvO4jzSIb55KAiDnCf2KkXRbbdxRg6cmxLbi8OgnjAYSTxTAtswhjA/t3Ya64xF",
	"+s+yLSBhWQpqbfVRu+22vulyzoTsvui86OixrlfL9wYTa7dJlvcxOtc/Vk8D1Km7cnKIzlWP5QirW4XD",
	"xj8tUb7mpWF1nq9h9i2vG19cf9ft3GhNsFC6bM4jKb3hLHEvqCxuXW9NcPQB4idVDpV18fo0vap9cMac",
	"Mu676dEZWovs7fXtfwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
