// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for AccountStatus.
const (
	ACTIVE      AccountStatus = "ACTIVE"
	DEACTIVATED AccountStatus = "DEACTIVATED"
	LOCKED      AccountStatus = "LOCKED"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case DEACTIVATED:
		return true
	case LOCKED:
		return true
	default:
		return false
	}
}

// Defines values for AuditEventType.
const (
	PASSWORDCHANGED        AuditEventType = "PASSWORD_CHANGED"
	PASSWORDRESETREQUESTED AuditEventType = "PASSWORD_RESET_REQUESTED"
	RELATIONSHIPGRANTED    AuditEventType = "RELATIONSHIP_GRANTED"
	RELATIONSHIPREVOKED    AuditEventType = "RELATIONSHIP_REVOKED"
	ROLECHANGED            AuditEventType = "ROLE_CHANGED"
	USERDEACTIVATED        AuditEventType = "USER_DEACTIVATED"
	USERLOCKED             AuditEventType = "USER_LOCKED"
	USERLOGIN              AuditEventType = "USER_LOGIN"
	USERLOGOUT             AuditEventType = "USER_LOGOUT"
	USERREGISTERED         AuditEventType = "USER_REGISTERED"
)

// Valid indicates whether the value is a known member of the AuditEventType enum.
func (e AuditEventType) Valid() bool {
	switch e {
	case PASSWORDCHANGED:
		return true
	case PASSWORDRESETREQUESTED:
		return true
	case RELATIONSHIPGRANTED:
		return true
	case RELATIONSHIPREVOKED:
		return true
	case ROLECHANGED:
		return true
	case USERDEACTIVATED:
		return true
	case USERLOCKED:
		return true
	case USERLOGIN:
		return true
	case USERLOGOUT:
		return true
	case USERREGISTERED:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleADMIN Role = "ADMIN"
	RoleUSER  Role = "USER"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleADMIN:
		return true
	case RoleUSER:
		return true
	default:
		return false
	}
}

// Defines values for UserType.
const (
	UserTypeDEVICE         UserType = "DEVICE"
	UserTypeSERVICEACCOUNT UserType = "SERVICE_ACCOUNT"
	UserTypeUSER           UserType = "USER"
)

// Valid indicates whether the value is a known member of the UserType enum.
func (e UserType) Valid() bool {
	switch e {
	case UserTypeDEVICE:
		return true
	case UserTypeSERVICEACCOUNT:
		return true
	case UserTypeUSER:
		return true
	default:
		return false
	}
}

// Defines values for UserBaseType.
const (
	DEVICE         UserBaseType = "DEVICE"
	SERVICEACCOUNT UserBaseType = "SERVICE_ACCOUNT"
	USER           UserBaseType = "USER"
)

// Valid indicates whether the value is a known member of the UserBaseType enum.
func (e UserBaseType) Valid() bool {
	switch e {
	case DEVICE:
		return true
	case SERVICEACCOUNT:
		return true
	case USER:
		return true
	default:
		return false
	}
}

// AccountStatus Lifecycle status of a user's account
type AccountStatus string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	// ActorId Universally Unique Lexicographically Sortable Identifier
	ActorId *ULID `json:"actorId,omitempty"`

	// EventType Category of a security-sensitive event captured in the audit log
	EventType AuditEventType `json:"eventType"`

	// Id Universally Unique Lexicographically Sortable Identifier
	Id ULID `json:"id"`

	// Metadata Event-specific contextual details
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// OccurredAt Timestamp at which the event occurred
	OccurredAt time.Time `json:"occurredAt"`

	// UserId Universally Unique Lexicographically Sortable Identifier
	UserId *ULID `json:"userId,omitempty"`
}

// AuditEventList defines model for AuditEventList.
type AuditEventList struct {
	Items []AuditEvent `json:"items"`

	// NextCursor Opaque cursor to fetch the next page, absent when there are no more results
	NextCursor *string `json:"nextCursor,omitempty"`
}

// AuditEventType Category of a security-sensitive event captured in the audit log
type AuditEventType string

// CheckRequest defines model for CheckRequest.
type CheckRequest struct {
	// Object Resource to check the relation against, in `type:id` form
	Object string `json:"object"`

	// Relation Relation to check
	Relation string `json:"relation"`

	// User Subject to check, in `type:id` form
	User string `json:"user"`
}

// CheckResponse defines model for CheckResponse.
type CheckResponse struct {
	// Allowed Whether the subject holds the requested relation on the object
	Allowed bool `json:"allowed"`
}

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error code or type
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Password User's password
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Opaque access token
	AccessToken string `json:"accessToken"`

	// ExpiresIn Token expiration time in seconds
	ExpiresIn int `json:"expiresIn"`

	// RefreshToken Opaque refresh token, rotated on each use
	RefreshToken string `json:"refreshToken"`

	// TokenType Token type
	TokenType string `json:"tokenType"`
	User      User   `json:"user"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	// Message Response message
	Message string `json:"message"`
}

// PasswordResetConfirm defines model for PasswordResetConfirm.
type PasswordResetConfirm struct {
	// NewPassword New password (minimum 8 characters)
	NewPassword string `json:"newPassword"`

	// Token Password reset token received via email
	Token string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	// Email User's email address
	Email openapi_types.Email `json:"email"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	// RefreshToken Refresh token previously issued at login or a prior refresh
	RefreshToken string `json:"refreshToken"`
}

// RelationshipTuple defines model for RelationshipTuple.
type RelationshipTuple struct {
	// Object Resource the relation applies to, in `type:id` form (e.g. `document:123`)
	Object string `json:"object"`

	// Relation Named relation between the user and the object (e.g. `owner`, `viewer`, `admin`)
	Relation string `json:"relation"`

	// User Subject of the relationship, in `type:id` form (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)
	User string `json:"user"`
}

// RelationshipTupleList defines model for RelationshipTupleList.
type RelationshipTupleList struct {
	Items []RelationshipTuple `json:"items"`
}

// Role Coarse-grained role assigned to a principal. Fine-grained permissions are evaluated via the Authorization (OpenFGA) endpoints.
type Role string

// ULID Universally Unique Lexicographically Sortable Identifier
type ULID = string

// User defines model for User.
type User struct {
	// Email User's unique email address (login identifier)
	Email openapi_types.Email `json:"email"`

	// FirstName User's first name
	FirstName *string `json:"firstName,omitempty"`

	// Id Universally Unique Lexicographically Sortable Identifier
	Id ULID `json:"id"`

	// LastName User's last name
	LastName *string `json:"lastName,omitempty"`

	// Locale User's locale
	Locale *string `json:"locale,omitempty"`

	// Role Coarse-grained role assigned to a principal. Fine-grained permissions are evaluated via the Authorization (OpenFGA) endpoints.
	Role *Role `json:"role,omitempty"`

	// Status Lifecycle status of a user's account
	Status *AccountStatus `json:"status,omitempty"`

	// Timezone User's timezone
	Timezone *string `json:"timezone,omitempty"`

	// Type Principal type for extensibility
	Type UserType `json:"type"`
}

// UserType Principal type for extensibility
type UserType string

// UserAdminUpdateRequest defines model for UserAdminUpdateRequest.
type UserAdminUpdateRequest struct {
	// Role Coarse-grained role assigned to a principal. Fine-grained permissions are evaluated via the Authorization (OpenFGA) endpoints.
	Role *Role `json:"role,omitempty"`

	// Status Lifecycle status of a user's account
	Status *AccountStatus `json:"status,omitempty"`
}

// UserBase defines model for UserBase.
type UserBase struct {
	// Email User's unique email address (login identifier)
	Email openapi_types.Email `json:"email"`

	// Id Universally Unique Lexicographically Sortable Identifier
	Id ULID `json:"id"`

	// Role Coarse-grained role assigned to a principal. Fine-grained permissions are evaluated via the Authorization (OpenFGA) endpoints.
	Role *Role `json:"role,omitempty"`

	// Status Lifecycle status of a user's account
	Status *AccountStatus `json:"status,omitempty"`

	// Type Principal type for extensibility
	Type UserBaseType `json:"type"`
}

// UserBaseType Principal type for extensibility
type UserBaseType string

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	// Email User's unique email address (login identifier)
	Email openapi_types.Email `json:"email"`

	// FirstName User's first name
	FirstName *string `json:"firstName,omitempty"`

	// LastName User's last name
	LastName *string `json:"lastName,omitempty"`

	// Locale User's locale
	Locale *string `json:"locale,omitempty"`

	// Password User's password (minimum 8 characters)
	Password string `json:"password"`

	// Timezone User's timezone
	Timezone *string `json:"timezone,omitempty"`
}

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	// Email User's unique email address (login identifier)
	Email openapi_types.Email `json:"email"`

	// Password User's password (minimum 8 characters)
	Password string `json:"password"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Items []User `json:"items"`

	// NextCursor Opaque cursor to fetch the next page, absent when there are no more results
	NextCursor *string `json:"nextCursor,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	// FirstName User's first name
	FirstName *string `json:"firstName,omitempty"`

	// LastName User's last name
	LastName *string `json:"lastName,omitempty"`

	// Locale User's locale
	Locale *string `json:"locale,omitempty"`

	// Timezone User's timezone
	Timezone *string `json:"timezone,omitempty"`
}

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	// FirstName User's first name
	FirstName *string `json:"firstName,omitempty"`

	// LastName User's last name
	LastName *string `json:"lastName,omitempty"`

	// Locale User's locale
	Locale *string `json:"locale,omitempty"`

	// Timezone User's timezone
	Timezone *string `json:"timezone,omitempty"`
}

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	// UserId Filter events by the affected user's ID
	UserId *ULID `form:"userId,omitempty" json:"userId,omitempty"`

	// EventType Filter events by type
	EventType *AuditEventType `form:"eventType,omitempty" json:"eventType,omitempty"`

	// From Only return events that occurred at or after this timestamp
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Only return events that occurred at or before this timestamp
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ConfirmUserRegistrationParams defines parameters for ConfirmUserRegistration.
type ConfirmUserRegistrationParams struct {
	// Token Confirmation token sent to the user's email
	Token string `form:"token" json:"token"`
}

// ListRelationshipsParams defines parameters for ListRelationships.
type ListRelationshipsParams struct {
	// Object Filter tuples by object (e.g. `document:123`)
	Object *string `form:"object,omitempty" json:"object,omitempty"`

	// User Filter tuples by user (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)
	User *string `form:"user,omitempty" json:"user,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit Maximum number of users to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// LogoutUserJSONRequestBody defines body for LogoutUser for application/json ContentType.
type LogoutUserJSONRequestBody = RefreshTokenRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = PasswordResetConfirm

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// RefreshAccessTokenJSONRequestBody defines body for RefreshAccessToken for application/json ContentType.
type RefreshAccessTokenJSONRequestBody = RefreshTokenRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserCreateRequest

// CheckPermissionJSONRequestBody defines body for CheckPermission for application/json ContentType.
type CheckPermissionJSONRequestBody = CheckRequest

// DeleteRelationshipJSONRequestBody defines body for DeleteRelationship for application/json ContentType.
type DeleteRelationshipJSONRequestBody = RelationshipTuple

// CreateRelationshipJSONRequestBody defines body for CreateRelationship for application/json ContentType.
type CreateRelationshipJSONRequestBody = RelationshipTuple

// UpdateUserProfileJSONRequestBody defines body for UpdateUserProfile for application/json ContentType.
type UpdateUserProfileJSONRequestBody = UserUpdateRequest

// UpdateUserAdminJSONRequestBody defines body for UpdateUserAdmin for application/json ContentType.
type UpdateUserAdminJSONRequestBody = UserAdminUpdateRequest
