/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Luciole Authentication Service API
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.0.1
 */

export interface LoginRequest {
  /** User's email address */
  email: string;
  /** User's password */
  password: string;
}
