/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Luciole Authentication Service API
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.0.1
 */
import type { User } from './user';

export interface LoginResponse {
  /** Opaque access token */
  accessToken: string;
  /** Token type */
  tokenType: string;
  /** Token expiration time in seconds */
  expiresIn: number;
  user: User;
}
