/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Luciole Authentication Service API
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.0.1
 */
import type { Ulid } from './ulid';
import type { UserBaseType } from './userBaseType';

export interface UserBase {
  /** The user id */
  id: Ulid;
  /** Principal type for extensibility */
  type: UserBaseType;
  /** User's unique email address (login identifier) */
  email: string;
}
