/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Sends a password reset link to the user's email
 * @summary Request password reset
 */
export const RequestPasswordResetBody = zod.object({
  "email": zod.email().describe('User\'s email address')
})

export const RequestPasswordResetResponse = zod.object({
  "message": zod.string().describe('Response message')
})

/**
 * Resets the user's password using a valid reset token
 * @summary Reset password
 */
export const resetPasswordBodyNewPasswordMin = 8;



export const ResetPasswordBody = zod.object({
  "token": zod.string().describe('Password reset token received via email'),
  "newPassword": zod.string().min(resetPasswordBodyNewPasswordMin).describe('New password (minimum 8 characters)')
})

export const ResetPasswordResponse = zod.object({
  "message": zod.string().describe('Response message')
})

