/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Creates a new user account with the provided credentials
 * @summary Register a new user
 */
export const registerUserBodyOnePasswordMin = 8;



export const RegisterUserBody = zod.object({
  "email": zod.email().describe('User\'s unique email address (login identifier)'),
  "password": zod.string().min(registerUserBodyOnePasswordMin).describe('User\'s password (minimum 8 characters)')
}).and(zod.object({
  "firstName": zod.string().optional().describe('User\'s first name'),
  "lastName": zod.string().optional().describe('User\'s last name'),
  "locale": zod.string().optional().describe('User\'s locale'),
  "timezone": zod.string().optional().describe('User\'s timezone')
}))

export const registerUserResponseOneIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');


export const RegisterUserResponse = zod.object({
  "id": zod.string().regex(registerUserResponseOneIdRegExp).describe('The user id'),
  "type": zod.enum(['USER', 'SERVICE_ACCOUNT', 'DEVICE']).describe('Principal type for extensibility'),
  "email": zod.email().describe('User\'s unique email address (login identifier)')
}).and(zod.object({
  "firstName": zod.string().optional().describe('User\'s first name'),
  "lastName": zod.string().optional().describe('User\'s last name'),
  "locale": zod.string().optional().describe('User\'s locale'),
  "timezone": zod.string().optional().describe('User\'s timezone')
}))

/**
 * Confirms a user's email address using a confirmation token
 * @summary Confirm user registration
 */
export const ConfirmUserRegistrationQueryParams = zod.object({
  "token": zod.string().describe('Confirmation token sent to the user\'s email')
})

export const ConfirmUserRegistrationResponse = zod.object({
  "message": zod.string().describe('Response message')
})

/**
 * Authenticates a user for browser-based clients (SPAs). The access token is never
 * exposed in the response body — it is issued as an HttpOnly cookie so that page
 * JavaScript cannot read it, which prevents XSS-based token theft. Mobile apps and
 * server-to-server clients that manage their own secure token storage should use
 * `POST /authn/token` instead, which returns the token in the response body.
 * @summary User login (browser / SPA session)
 */
export const LoginUserBody = zod.object({
  "email": zod.email().describe('User\'s email address'),
  "password": zod.string().describe('User\'s password')
})

export const LoginUserResponse = zod.object({
  "message": zod.string().describe('Response message')
})

/**
 * Authenticates a user or service and returns an opaque access token and refresh
 * token in the response body. Intended for native mobile apps and machine-to-machine
 * clients that store tokens in OS-level secure storage (Keychain, Keystore, a secrets
 * vault) rather than a browser document, so they are not exposed to DOM-based XSS.
 * Browser-based SPAs should use `POST /authn/login` instead, which never returns the
 * token in the body.
 * @summary User login (mobile / server-to-server)
 */
export const IssueTokenBody = zod.object({
  "email": zod.email().describe('User\'s email address'),
  "password": zod.string().describe('User\'s password')
})

export const IssueTokenResponse = zod.object({
  "accessToken": zod.string().describe('Opaque access token'),
  "tokenType": zod.string().describe('Token type'),
  "expiresIn": zod.number().describe('Token expiration time in seconds'),
  "refreshToken": zod.string().describe('Opaque refresh token, rotated on each use')
})

/**
 * Exchanges a valid refresh token for a new access token, rotating the refresh token
 * @summary Refresh access token
 */
export const RefreshAccessTokenBody = zod.object({
  "refreshToken": zod.string().describe('Refresh token previously issued at login or a prior refresh')
})

export const RefreshAccessTokenResponse = zod.object({
  "accessToken": zod.string().describe('Opaque access token'),
  "tokenType": zod.string().describe('Token type'),
  "expiresIn": zod.number().describe('Token expiration time in seconds'),
  "refreshToken": zod.string().describe('Opaque refresh token, rotated on each use')
})

/**
 * Invalidates the current user's access token and revokes the associated refresh token
 * @summary User logout
 */
export const LogoutUserBody = zod.object({
  "refreshToken": zod.string().describe('Refresh token previously issued at login or a prior refresh')
})

export const LogoutUserResponse = zod.void()

