/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Retrieves the authenticated user's profile information
 * @summary Get user profile
 */
export const getUserProfileResponseOneIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');
export const getUserProfileResponseOneRoleDefault = `USER`;
export const getUserProfileResponseOneStatusDefault = `ACTIVE`;

export const GetUserProfileResponse = zod.object({
  "id": zod.string().regex(getUserProfileResponseOneIdRegExp).describe('The user id'),
  "type": zod.enum(['USER', 'SERVICE_ACCOUNT', 'DEVICE']).describe('Principal type for extensibility'),
  "email": zod.email().describe('User\'s unique email address (login identifier)'),
  "role": zod.enum(['ADMIN', 'USER']).default(getUserProfileResponseOneRoleDefault).describe('Coarse-grained role assigned to a principal. Fine-grained permissions are evaluated via the Authorization (OpenFGA) endpoints.'),
  "status": zod.enum(['ACTIVE', 'LOCKED', 'DEACTIVATED']).default(getUserProfileResponseOneStatusDefault).describe('Lifecycle status of a user\'s account')
}).and(zod.object({
  "firstName": zod.string().optional().describe('User\'s first name'),
  "lastName": zod.string().optional().describe('User\'s last name'),
  "locale": zod.string().optional().describe('User\'s locale'),
  "timezone": zod.string().optional().describe('User\'s timezone')
}))

/**
 * Updates the authenticated user's profile information
 * @summary Update user profile
 */
export const UpdateUserProfileBody = zod.object({
  "firstName": zod.string().optional().describe('User\'s first name'),
  "lastName": zod.string().optional().describe('User\'s last name'),
  "locale": zod.string().optional().describe('User\'s locale'),
  "timezone": zod.string().optional().describe('User\'s timezone')
})

export const updateUserProfileResponseOneIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');
export const updateUserProfileResponseOneRoleDefault = `USER`;
export const updateUserProfileResponseOneStatusDefault = `ACTIVE`;

export const UpdateUserProfileResponse = zod.object({
  "id": zod.string().regex(updateUserProfileResponseOneIdRegExp).describe('The user id'),
  "type": zod.enum(['USER', 'SERVICE_ACCOUNT', 'DEVICE']).describe('Principal type for extensibility'),
  "email": zod.email().describe('User\'s unique email address (login identifier)'),
  "role": zod.enum(['ADMIN', 'USER']).default(updateUserProfileResponseOneRoleDefault).describe('Coarse-grained role assigned to a principal. Fine-grained permissions are evaluated via the Authorization (OpenFGA) endpoints.'),
  "status": zod.enum(['ACTIVE', 'LOCKED', 'DEACTIVATED']).default(updateUserProfileResponseOneStatusDefault).describe('Lifecycle status of a user\'s account')
}).and(zod.object({
  "firstName": zod.string().optional().describe('User\'s first name'),
  "lastName": zod.string().optional().describe('User\'s last name'),
  "locale": zod.string().optional().describe('User\'s locale'),
  "timezone": zod.string().optional().describe('User\'s timezone')
}))

/**
 * Deactivates the authenticated user's own account
 * @summary Delete own account
 */
export const DeleteUserProfileResponse = zod.void()

