/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Retrieves a user by their unique identifier
 * @summary Get user by ID
 */
export const getUserByIDPathIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');


export const GetUserByIDParams = zod.object({
  "id": zod.string().regex(getUserByIDPathIdRegExp).describe('User\'s unique identifier')
})

export const getUserByIDResponseOneIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');


export const GetUserByIDResponse = zod.object({
  "id": zod.string().regex(getUserByIDResponseOneIdRegExp).describe('The user id'),
  "type": zod.enum(['USER', 'SERVICE_ACCOUNT', 'DEVICE']).describe('Principal type for extensibility'),
  "email": zod.email().describe('User\'s unique email address (login identifier)')
}).and(zod.object({
  "firstName": zod.string().optional().describe('User\'s first name'),
  "lastName": zod.string().optional().describe('User\'s last name'),
  "locale": zod.string().optional().describe('User\'s locale'),
  "timezone": zod.string().optional().describe('User\'s timezone')
}))

