/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AuditEventMetadata } from './auditEventMetadata';
import type { AuditEventType } from './auditEventType';
import type { Ulid } from './ulid';

export interface AuditEvent {
  id: Ulid;
  eventType: AuditEventType;
  userId?: Ulid;
  /** Identifier of the principal who performed the action, when different from userId (e.g. an admin locking another user's account) */
  actorId?: Ulid;
  /** Timestamp at which the event occurred */
  occurredAt: string;
  /** Event-specific contextual details */
  metadata?: AuditEventMetadata;
}
