/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */

/**
 * Category of a security-sensitive event captured in the audit log
 */
export type AuditEventType = typeof AuditEventType[keyof typeof AuditEventType];


export const AuditEventType = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOCKED: 'USER_LOCKED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  RELATIONSHIP_GRANTED: 'RELATIONSHIP_GRANTED',
  RELATIONSHIP_REVOKED: 'RELATIONSHIP_REVOKED',
} as const;
