/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface CheckRequest {
  /** Subject to check, in `type:id` form */
  user: string;
  /** Relation to check */
  relation: string;
  /** Resource to check the relation against, in `type:id` form */
  object: string;
}
