/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorDetails } from './errorDetails';

export interface Error {
  /** Error code or type */
  error: string;
  /** Human-readable error message */
  message: string;
  /** Additional error details */
  details?: ErrorDetails;
}
