/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AuditEventType } from './auditEventType';
import type { Ulid } from './ulid';

export type ListAuditLogsParams = {
/**
 * Filter events by the affected user's ID
 */
userId?: Ulid;
/**
 * Filter events by type
 */
eventType?: AuditEventType;
/**
 * Only return events that occurred at or after this timestamp
 */
from?: string;
/**
 * Only return events that occurred at or before this timestamp
 */
to?: string;
/**
 * Maximum number of events to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Opaque pagination cursor from a previous response
 */
cursor?: string;
};
