/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */

export type ListRelationshipsParams = {
/**
 * Filter tuples by object (e.g. `document:123`)
 */
object?: string;
/**
 * Filter tuples by user (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)
 */
user?: string;
};
