/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { User } from './user';

export interface LoginResponse {
  /** Opaque access token */
  accessToken: string;
  /** Token type */
  tokenType: string;
  /** Token expiration time in seconds */
  expiresIn: number;
  /** Opaque refresh token, rotated on each use */
  refreshToken: string;
  user: User;
}
