/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface PasswordResetConfirm {
  /** Password reset token received via email */
  token: string;
  /**
     * New password (minimum 8 characters)
     * @minLength 8
     */
  newPassword: string;
}
