/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface TokenResponse {
  /** Opaque access token */
  accessToken: string;
  /** Token type */
  tokenType: string;
  /** Token expiration time in seconds */
  expiresIn: number;
  /** Opaque refresh token, rotated on each use */
  refreshToken: string;
}
