/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AccountStatus } from './accountStatus';
import type { Ulid } from './ulid';
import type { UserBaseType } from './userBaseType';

export interface UserBase {
  /** The user id */
  id: Ulid;
  /** Principal type for extensibility */
  type: UserBaseType;
  /** User's unique email address (login identifier) */
  email: string;
  status?: AccountStatus;
}
