/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { UserCredentials } from './userCredentials';
import type { UserProfile } from './userProfile';

export type UserCreateRequest = UserCredentials & UserProfile;
