/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AccountStatus } from './accountStatus';
import type { Role } from './role';

export interface UserAdminUpdateRequest {
  role?: Role;
  status?: AccountStatus;
}
