/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface UserProfile {
  /** User's first name */
  firstName?: string;
  /** User's last name */
  lastName?: string;
  /** User's locale */
  locale?: string;
  /** User's timezone */
  timezone?: string;
}
