/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns 200 OK if the process is running.
 * @summary Liveness check
 */
export const CheckLivenessResponse = zod.unknown()

/**
 * Returns 200 OK if all critical services are healthy, 503 Service Unavailable otherwise.
 * @summary Readiness check
 */
export const CheckReadinessResponse = zod.object({
  "status": zod.string()
})

