/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Checks whether a user has a given relation to an object, delegating the decision to the OpenFGA store
 * @summary Check a permission
 */
export const CheckPermissionBody = zod.object({
  "user": zod.string().describe('Subject to check, in `type:id` form'),
  "relation": zod.string().describe('Relation to check'),
  "object": zod.string().describe('Resource to check the relation against, in `type:id` form')
})

export const CheckPermissionResponse = zod.object({
  "allowed": zod.boolean().describe('Whether the subject holds the requested relation on the object')
})

/**
 * Lists OpenFGA relationship tuples, optionally filtered by object or user
 * @summary List relationship tuples
 */
export const ListRelationshipsQueryParams = zod.object({
  "object": zod.string().optional().describe('Filter tuples by object (e.g. `document:123`)'),
  "user": zod.string().optional().describe('Filter tuples by user (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)')
})

export const ListRelationshipsResponse = zod.object({
  "items": zod.array(zod.object({
  "user": zod.string().describe('Subject of the relationship, in `type:id` form (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)'),
  "relation": zod.string().describe('Named relation between the user and the object (e.g. `owner`, `viewer`, `admin`)'),
  "object": zod.string().describe('Resource the relation applies to, in `type:id` form (e.g. `document:123`)')
}))
})

/**
 * Writes a new relationship tuple to the OpenFGA store (e.g. granting a user a role on a resource). Requires an administrative role.
 * @summary Create a relationship tuple
 */
export const CreateRelationshipBody = zod.object({
  "user": zod.string().describe('Subject of the relationship, in `type:id` form (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)'),
  "relation": zod.string().describe('Named relation between the user and the object (e.g. `owner`, `viewer`, `admin`)'),
  "object": zod.string().describe('Resource the relation applies to, in `type:id` form (e.g. `document:123`)')
})

export const CreateRelationshipResponse = zod.object({
  "user": zod.string().describe('Subject of the relationship, in `type:id` form (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)'),
  "relation": zod.string().describe('Named relation between the user and the object (e.g. `owner`, `viewer`, `admin`)'),
  "object": zod.string().describe('Resource the relation applies to, in `type:id` form (e.g. `document:123`)')
})

/**
 * Removes an existing relationship tuple from the OpenFGA store (e.g. revoking a role). Requires an administrative role.
 * @summary Delete a relationship tuple
 */
export const DeleteRelationshipBody = zod.object({
  "user": zod.string().describe('Subject of the relationship, in `type:id` form (e.g. `user:01H8R5X7X9Y2Z4W6V8T0S1Q2R`)'),
  "relation": zod.string().describe('Named relation between the user and the object (e.g. `owner`, `viewer`, `admin`)'),
  "object": zod.string().describe('Resource the relation applies to, in `type:id` form (e.g. `document:123`)')
})

export const DeleteRelationshipResponse = zod.void()

