/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Luciole Authentication Service API
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.0.1
 */
/**
 * Universally Unique Lexicographically Sortable Identifier
 * @pattern ^[0-9A-HJKMNP-TV-Z]{26}$
 */
export type Ulid = string;

/**
 * Principal type for extensibility
 */
export type UserBaseType = typeof UserBaseType[keyof typeof UserBaseType];


export const UserBaseType = {
  USER: 'USER',
  SERVICE_ACCOUNT: 'SERVICE_ACCOUNT',
  DEVICE: 'DEVICE',
} as const;

export interface UserBase {
  /** The user id */
  id: Ulid;
  /** Principal type for extensibility */
  type: UserBaseType;
  /** User's unique email address (login identifier) */
  email: string;
}

export interface UserCredentials {
  /** User's unique email address (login identifier) */
  email: string;
  /**
     * User's password (minimum 8 characters)
     * @minLength 8
     */
  password: string;
}

export interface UserProfile {
  /** User's first name */
  firstName?: string;
  /** User's last name */
  lastName?: string;
  /** User's locale */
  locale?: string;
  /** User's timezone */
  timezone?: string;
}

export type User = UserBase & UserProfile;

export type UserCreateRequest = UserCredentials & UserProfile;

export interface UserUpdateRequest {
  /** User's first name */
  firstName?: string;
  /** User's last name */
  lastName?: string;
  /** User's locale */
  locale?: string;
  /** User's timezone */
  timezone?: string;
}

export interface LoginRequest {
  /** User's email address */
  email: string;
  /** User's password */
  password: string;
}

export interface LoginResponse {
  /** Opaque access token */
  accessToken: string;
  /** Token type */
  tokenType: string;
  /** Token expiration time in seconds */
  expiresIn: number;
  user: User;
}

export interface PasswordResetRequest {
  /** User's email address */
  email: string;
}

export interface PasswordResetConfirm {
  /** Password reset token received via email */
  token: string;
  /**
     * New password (minimum 8 characters)
     * @minLength 8
     */
  newPassword: string;
}

export interface MessageResponse {
  /** Response message */
  message: string;
}

/**
 * Additional error details
 */
export type ErrorDetails = { [key: string]: unknown };

export interface Error {
  /** Error code or type */
  error: string;
  /** Human-readable error message */
  message: string;
  /** Additional error details */
  details?: ErrorDetails;
}

/**
 * Service Temporarily Unavailable or Degraded
 */
export type ServiceUnavailableResponse = Error;

export type CheckReadiness200 = {
  status: string;
};

export type ConfirmUserRegistrationParams = {
/**
 * Confirmation token sent to the user's email
 */
token: string;
};

export type checkLivenessResponse200 = {
  data: void
  status: 200
}

export type checkLivenessResponseSuccess = (checkLivenessResponse200) & {
  headers: Headers;
};
;

export type checkLivenessResponse = (checkLivenessResponseSuccess)

export const getCheckLivenessUrl = () => {




  return `/live`
}

/**
 * Returns 200 OK if the process is running.
 * @summary Liveness check
 */
export const checkLiveness = async ( options?: RequestInit): Promise<checkLivenessResponse> => {

  const res = await fetch(getCheckLivenessUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: checkLivenessResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as checkLivenessResponse
}



export type checkReadinessResponse200 = {
  data: CheckReadiness200
  status: 200
}

export type checkReadinessResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type checkReadinessResponseSuccess = (checkReadinessResponse200) & {
  headers: Headers;
};
export type checkReadinessResponseError = (checkReadinessResponse503) & {
  headers: Headers;
};

export type checkReadinessResponse = (checkReadinessResponseSuccess | checkReadinessResponseError)

export const getCheckReadinessUrl = () => {




  return `/ready`
}

/**
 * Returns 200 OK if all critical services are healthy, 503 Service Unavailable otherwise.
 * @summary Readiness check
 */
export const checkReadiness = async ( options?: RequestInit): Promise<checkReadinessResponse> => {

  const res = await fetch(getCheckReadinessUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: checkReadinessResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkReadinessResponse
}



export type registerUserResponse201 = {
  data: User
  status: 201
}

export type registerUserResponse400 = {
  data: Error
  status: 400
}

export type registerUserResponse409 = {
  data: Error
  status: 409
}

export type registerUserResponse500 = {
  data: Error
  status: 500
}

export type registerUserResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type registerUserResponseSuccess = (registerUserResponse201) & {
  headers: Headers;
};
export type registerUserResponseError = (registerUserResponse400 | registerUserResponse409 | registerUserResponse500 | registerUserResponse503) & {
  headers: Headers;
};

export type registerUserResponse = (registerUserResponseSuccess | registerUserResponseError)

export const getRegisterUserUrl = () => {




  return `/authn/register`
}

/**
 * Creates a new user account with the provided credentials
 * @summary Register a new user
 */
export const registerUser = async (userCreateRequest: UserCreateRequest, options?: RequestInit): Promise<registerUserResponse> => {

  const res = await fetch(getRegisterUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreateRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerUserResponse
}



export type confirmUserRegistrationResponse200 = {
  data: MessageResponse
  status: 200
}

export type confirmUserRegistrationResponse400 = {
  data: Error
  status: 400
}

export type confirmUserRegistrationResponse410 = {
  data: Error
  status: 410
}

export type confirmUserRegistrationResponse500 = {
  data: Error
  status: 500
}

export type confirmUserRegistrationResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type confirmUserRegistrationResponseSuccess = (confirmUserRegistrationResponse200) & {
  headers: Headers;
};
export type confirmUserRegistrationResponseError = (confirmUserRegistrationResponse400 | confirmUserRegistrationResponse410 | confirmUserRegistrationResponse500 | confirmUserRegistrationResponse503) & {
  headers: Headers;
};

export type confirmUserRegistrationResponse = (confirmUserRegistrationResponseSuccess | confirmUserRegistrationResponseError)

export const getConfirmUserRegistrationUrl = (params: ConfirmUserRegistrationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/authn/confirm?${stringifiedParams}` : `/authn/confirm`
}

/**
 * Confirms a user's email address using a confirmation token
 * @summary Confirm user registration
 */
export const confirmUserRegistration = async (params: ConfirmUserRegistrationParams, options?: RequestInit): Promise<confirmUserRegistrationResponse> => {

  const res = await fetch(getConfirmUserRegistrationUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: confirmUserRegistrationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as confirmUserRegistrationResponse
}



export type loginUserResponse200 = {
  data: LoginResponse
  status: 200
}

export type loginUserResponse400 = {
  data: Error
  status: 400
}

export type loginUserResponse401 = {
  data: Error
  status: 401
}

export type loginUserResponse500 = {
  data: Error
  status: 500
}

export type loginUserResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type loginUserResponseSuccess = (loginUserResponse200) & {
  headers: Headers;
};
export type loginUserResponseError = (loginUserResponse400 | loginUserResponse401 | loginUserResponse500 | loginUserResponse503) & {
  headers: Headers;
};

export type loginUserResponse = (loginUserResponseSuccess | loginUserResponseError)

export const getLoginUserUrl = () => {




  return `/authn/login`
}

/**
 * Authenticates a user and returns an opaque access token
 * @summary User login
 */
export const loginUser = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginUserResponse> => {

  const res = await fetch(getLoginUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginUserResponse
}



export type logoutUserResponse204 = {
  data: void
  status: 204
}

export type logoutUserResponse401 = {
  data: Error
  status: 401
}

export type logoutUserResponse500 = {
  data: Error
  status: 500
}

export type logoutUserResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type logoutUserResponseSuccess = (logoutUserResponse204) & {
  headers: Headers;
};
export type logoutUserResponseError = (logoutUserResponse401 | logoutUserResponse500 | logoutUserResponse503) & {
  headers: Headers;
};

export type logoutUserResponse = (logoutUserResponseSuccess | logoutUserResponseError)

export const getLogoutUserUrl = () => {




  return `/authn/logout`
}

/**
 * Invalidates the current user's access token
 * @summary User logout
 */
export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {

  const res = await fetch(getLogoutUserUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: logoutUserResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as logoutUserResponse
}



export type requestPasswordResetResponse202 = {
  data: MessageResponse
  status: 202
}

export type requestPasswordResetResponse400 = {
  data: Error
  status: 400
}

export type requestPasswordResetResponse404 = {
  data: Error
  status: 404
}

export type requestPasswordResetResponse429 = {
  data: Error
  status: 429
}

export type requestPasswordResetResponse500 = {
  data: Error
  status: 500
}

export type requestPasswordResetResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type requestPasswordResetResponseSuccess = (requestPasswordResetResponse202) & {
  headers: Headers;
};
export type requestPasswordResetResponseError = (requestPasswordResetResponse400 | requestPasswordResetResponse404 | requestPasswordResetResponse429 | requestPasswordResetResponse500 | requestPasswordResetResponse503) & {
  headers: Headers;
};

export type requestPasswordResetResponse = (requestPasswordResetResponseSuccess | requestPasswordResetResponseError)

export const getRequestPasswordResetUrl = () => {




  return `/authn/password/reset-request`
}

/**
 * Sends a password reset link to the user's email
 * @summary Request password reset
 */
export const requestPasswordReset = async (passwordResetRequest: PasswordResetRequest, options?: RequestInit): Promise<requestPasswordResetResponse> => {

  const res = await fetch(getRequestPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(passwordResetRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: requestPasswordResetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as requestPasswordResetResponse
}



export type resetPasswordResponse200 = {
  data: MessageResponse
  status: 200
}

export type resetPasswordResponse400 = {
  data: Error
  status: 400
}

export type resetPasswordResponse410 = {
  data: Error
  status: 410
}

export type resetPasswordResponse500 = {
  data: Error
  status: 500
}

export type resetPasswordResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type resetPasswordResponseSuccess = (resetPasswordResponse200) & {
  headers: Headers;
};
export type resetPasswordResponseError = (resetPasswordResponse400 | resetPasswordResponse410 | resetPasswordResponse500 | resetPasswordResponse503) & {
  headers: Headers;
};

export type resetPasswordResponse = (resetPasswordResponseSuccess | resetPasswordResponseError)

export const getResetPasswordUrl = () => {




  return `/authn/password/reset`
}

/**
 * Resets the user's password using a valid reset token
 * @summary Reset password
 */
export const resetPassword = async (passwordResetConfirm: PasswordResetConfirm, options?: RequestInit): Promise<resetPasswordResponse> => {

  const res = await fetch(getResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(passwordResetConfirm)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: resetPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resetPasswordResponse
}



export type getUserProfileResponse200 = {
  data: User
  status: 200
}

export type getUserProfileResponse401 = {
  data: Error
  status: 401
}

export type getUserProfileResponse500 = {
  data: Error
  status: 500
}

export type getUserProfileResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type getUserProfileResponseSuccess = (getUserProfileResponse200) & {
  headers: Headers;
};
export type getUserProfileResponseError = (getUserProfileResponse401 | getUserProfileResponse500 | getUserProfileResponse503) & {
  headers: Headers;
};

export type getUserProfileResponse = (getUserProfileResponseSuccess | getUserProfileResponseError)

export const getGetUserProfileUrl = () => {




  return `/profile`
}

/**
 * Retrieves the authenticated user's profile information
 * @summary Get user profile
 */
export const getUserProfile = async ( options?: RequestInit): Promise<getUserProfileResponse> => {

  const res = await fetch(getGetUserProfileUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserProfileResponse
}



export type updateUserProfileResponse200 = {
  data: User
  status: 200
}

export type updateUserProfileResponse400 = {
  data: Error
  status: 400
}

export type updateUserProfileResponse401 = {
  data: Error
  status: 401
}

export type updateUserProfileResponse409 = {
  data: Error
  status: 409
}

export type updateUserProfileResponse500 = {
  data: Error
  status: 500
}

export type updateUserProfileResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type updateUserProfileResponseSuccess = (updateUserProfileResponse200) & {
  headers: Headers;
};
export type updateUserProfileResponseError = (updateUserProfileResponse400 | updateUserProfileResponse401 | updateUserProfileResponse409 | updateUserProfileResponse500 | updateUserProfileResponse503) & {
  headers: Headers;
};

export type updateUserProfileResponse = (updateUserProfileResponseSuccess | updateUserProfileResponseError)

export const getUpdateUserProfileUrl = () => {




  return `/profile`
}

/**
 * Updates the authenticated user's profile information
 * @summary Update user profile
 */
export const updateUserProfile = async (userUpdateRequest: UserUpdateRequest, options?: RequestInit): Promise<updateUserProfileResponse> => {

  const res = await fetch(getUpdateUserProfileUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdateRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateUserProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateUserProfileResponse
}



export type getUserByIDResponse200 = {
  data: User
  status: 200
}

export type getUserByIDResponse404 = {
  data: Error
  status: 404
}

export type getUserByIDResponse500 = {
  data: Error
  status: 500
}

export type getUserByIDResponse503 = {
  data: ServiceUnavailableResponse
  status: 503
}

export type getUserByIDResponseSuccess = (getUserByIDResponse200) & {
  headers: Headers;
};
export type getUserByIDResponseError = (getUserByIDResponse404 | getUserByIDResponse500 | getUserByIDResponse503) & {
  headers: Headers;
};

export type getUserByIDResponse = (getUserByIDResponseSuccess | getUserByIDResponseError)

export const getGetUserByIDUrl = (id: Ulid,) => {




  return `/users/${id}`
}

/**
 * Retrieves a user by their unique identifier
 * @summary Get user by ID
 */
export const getUserByID = async (id: Ulid, options?: RequestInit): Promise<getUserByIDResponse> => {

  const res = await fetch(getGetUserByIDUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserByIDResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserByIDResponse
}
