/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Beholder API Specification
 * API for user authentication, profile management, and password operations using opaque tokens.
 * Email is the unique primary identifier for all users.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of users. Requires an administrative role.
 * @summary List users
 */
export const listUsersQueryLimitDefault = 20;
export const listUsersQueryLimitMax = 100;



export const ListUsersQueryParams = zod.object({
  "limit": zod.number().min(1).max(listUsersQueryLimitMax).default(listUsersQueryLimitDefault).describe('Maximum number of users to return'),
  "cursor": zod.string().optional().describe('Opaque pagination cursor from a previous response')
})

export const listUsersResponseItemsItemOneIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');
export const listUsersResponseItemsItemOneStatusDefault = `ACTIVE`;

export const ListUsersResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().regex(listUsersResponseItemsItemOneIdRegExp).describe('The user id'),
  "type": zod.enum(['USER', 'SERVICE_ACCOUNT', 'DEVICE']).describe('Principal type for extensibility'),
  "email": zod.email().describe('User\'s unique email address (login identifier)'),
  "status": zod.enum(['ACTIVE', 'LOCKED', 'DEACTIVATED']).default(listUsersResponseItemsItemOneStatusDefault).describe('Lifecycle status of a user\'s account')
}).and(zod.object({
  "firstName": zod.string().optional().describe('User\'s first name'),
  "lastName": zod.string().optional().describe('User\'s last name'),
  "locale": zod.string().optional().describe('User\'s locale'),
  "timezone": zod.string().optional().describe('User\'s timezone')
}))),
  "nextCursor": zod.string().optional().describe('Opaque cursor to fetch the next page, absent when there are no more results')
})

/**
 * Deactivates another user's account. Requires an administrative role.
 * @summary Deactivate a user
 */
export const deactivateUserPathIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');


export const DeactivateUserParams = zod.object({
  "id": zod.string().regex(deactivateUserPathIdRegExp).describe('User\'s unique identifier')
})

export const DeactivateUserResponse = zod.void()

/**
 * Retrieves a paginated list of security-sensitive audit events, powering the admin dashboard's audit view. Requires an administrative role.
 * @summary List audit log events
 */
export const listAuditLogsQueryUserIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');
export const listAuditLogsQueryLimitDefault = 20;
export const listAuditLogsQueryLimitMax = 100;



export const ListAuditLogsQueryParams = zod.object({
  "userId": zod.string().regex(listAuditLogsQueryUserIdRegExp).optional().describe('Filter events by the affected user\'s ID'),
  "eventType": zod.enum(['USER_REGISTERED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_LOCKED', 'USER_DEACTIVATED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'ROLE_CHANGED', 'RELATIONSHIP_GRANTED', 'RELATIONSHIP_REVOKED']).optional().describe('Filter events by type'),
  "from": zod.iso.datetime({"offset":true}).optional().describe('Only return events that occurred at or after this timestamp'),
  "to": zod.iso.datetime({"offset":true}).optional().describe('Only return events that occurred at or before this timestamp'),
  "limit": zod.number().min(1).max(listAuditLogsQueryLimitMax).default(listAuditLogsQueryLimitDefault).describe('Maximum number of events to return'),
  "cursor": zod.string().optional().describe('Opaque pagination cursor from a previous response')
})

export const listAuditLogsResponseItemsItemIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');
export const listAuditLogsResponseItemsItemUserIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');
export const listAuditLogsResponseItemsItemActorIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');


export const ListAuditLogsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().regex(listAuditLogsResponseItemsItemIdRegExp).describe('Universally Unique Lexicographically Sortable Identifier'),
  "eventType": zod.enum(['USER_REGISTERED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_LOCKED', 'USER_DEACTIVATED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'ROLE_CHANGED', 'RELATIONSHIP_GRANTED', 'RELATIONSHIP_REVOKED']).describe('Category of a security-sensitive event captured in the audit log'),
  "userId": zod.string().regex(listAuditLogsResponseItemsItemUserIdRegExp).optional().describe('Universally Unique Lexicographically Sortable Identifier'),
  "actorId": zod.string().regex(listAuditLogsResponseItemsItemActorIdRegExp).optional().describe('Identifier of the principal who performed the action, when different from userId (e.g. an admin locking another user\'s account)'),
  "occurredAt": zod.iso.datetime({"offset":true}).describe('Timestamp at which the event occurred'),
  "metadata": zod.record(zod.string(), zod.unknown()).optional().describe('Event-specific contextual details')
})),
  "nextCursor": zod.string().optional().describe('Opaque cursor to fetch the next page, absent when there are no more results')
})

